### ISSUE TITLE
Basic Deduplication

### ISSUE THREAD

**Issue by allthesignals** [MAPC/rental-listing-aggregator#2]
Right now there are numerous duplicate records found in the results, specifically the Craigslist module. While duplication is generally a much more difficult issue that we'd like to solve, we can at least have the scraper identify when exact duplicate records are being pushed into the database.

We need to get a "sense of how often Craigslist listings are modified in a substantial way over their lifecycle" - @timstallmann suggested using unique listing URL.

**Comment by timstallmann** [comment]
Awesome! I'm working on this now in https://github.com/DataWorks-NC/rental-listing-aggregator/tree/basic-dedupe -- this uses the Craigslist URL or Padmapper listing ID as a unique identifier to tag listings in the database, and updates existing listings if they have already been scraped. For now, it also tracks a bit about whether listings have changed or not...

@JohnKilleen and I are planning to deploy the dedupe version of the code for a month or two and see if it seems like we're missing any significant data with the deduplication..
