### ISSUE TITLE
Region-specific JSON-search endpoint?

### ISSUE THREAD

**Issue by allthesignals** [MAPC/rental-listing-aggregator#8]
Boston: https://boston.craigslist.org/jsonsearch/aap/?map=1
Raleigh: https://raleigh.craigslist.org/jsonsearch/apa/?map=1

Probably calls for another environment variable in the docker-compose yaml.

**Comment by allthesignals** [comment]
Maybe some error-handling on the Net class error response - was buried under the classic "can't convert nil to string", but was unrelated really to type

**Comment by timstallmann** [comment]
This endpoint is set via the `CRAIGSLIST_URL` environment variable on the Ruby container -- see `docker-compose.yml`

**Comment by allthesignals** [comment]
I think the rest of the endpoint is coded here: https://github.com/MAPC/rental-listing-aggregator/blob/master/mux/craigslist.rb#L11 - can just make that also part of the "CRAIGSLIST_URL" env variable. 

I don't know how it works, but boston craigslist has no "apa" - so it's not consistent across regions.

**Comment by timstallmann** [comment]
Ohhhh I see! Yeah let's just do that...

**Comment by allthesignals** [comment]
I can work on it but wanted to make sure I wasn't misunderstanding :)
